version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - data_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  backend:
    image: rsateam/foodgram_backend:latest
    restart: always
    volumes:
      - ../frontend/build/static:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
      - frontend
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ../frontend/build/static:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  media_value:
  data_value:
