# Generated by Django 4.2.1 on 2023-05-20 23:08

from django.db import migrations, models

import tags.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Имя тега"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        help_text="Цвет тега в HEX-формате (#RRGGBB)",
                        max_length=7,
                        unique=True,
                        validators=[tags.models.color_code_validate],
                        verbose_name="Цвет",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=200,
                        unique=True,
                        verbose_name="Код тега (строка)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тэг",
                "verbose_name_plural": "Тэги",
                "ordering": ["id"],
            },
        ),
    ]
